--- # This task will install elasticsearch and config /etc/elasticsearch/elasticsearch.yml and /etc/elasticsearch/jvm.options

  - name: Install elasticsearch
    yum:
      name: elasticsearch
      state: latest

  - name: Copying elasticsearch.yml to /etc/elasticsearch/
    template:
      src: elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: elasticsearch
      group: elasticsearch
      mode: 0644

  - name: Modifying java max heap (1/2 of total memory size)
    lineinfile:
      path: /etc/elasticsearch/jvm.options
      regexp: '^-Xmx1g'
      line: "-Xmx{{ (ansible_memtotal_mb / 2) | int }}m"

  - name: Modifying java min heap (1/2 of total memory size)
    lineinfile:
      path: /etc/elasticsearch/jvm.options
      regexp: '^-Xms1g'
      line: "-Xms{{ (ansible_memtotal_mb / 2) | int }}m"

  - name: Restart and enabling elasticsearch server
    service :
      name: elasticsearch
      state: restarted
      enabled: yes
