--- # This task is adding elastic GPG KEY

  - name: Add an apt signing key, uses whichever key is at the URL
    rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Ansible create file if it doesn't exist
    file:
      path: /etc/yum.repos.d/
      state: file
      mode: 0644

  - name: Save the repository definition to /etc/yum.repos.d/elasticsearch.repo
    blockinfile:
      path: /etc/yum.repos.d/elasticsearch.repo
      block: |
        [elasticsearch-7.x]
        name=Elasticsearch repository for 7.x packages
        baseurl=https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck=1
        gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled=1
        autorefresh=1
        type=rpm-md
